### ISSUE TITLE
When files are attached to messages I'm not getting any options to change the size

### ISSUE THREAD

**Issue by a4jp-com** [darktrojan/shrunked#19]
When files are attached to messages I'm not getting any options to change the size. Is the code only working when the files are sent? It would be nice to set everything before sending files, that way I can have template messages ready to send off to people.

**Comment by darktrojan** [comment]
That's correct, attachments are resized at send time. It made sense when I first wrote it, but whether that's the right thing to do or not is debatable. I'll have a think about making a change.

**Comment by a4jp-com** [comment]
Thank you. I would be cool if we could right click any attachment listed and set the size at anytime if this isn't too difficult to get working.

**Comment by darktrojan** [comment]
You should find both options available with the latest release. Enjoy.
