### ISSUE TITLE
FileReader is not defined error

### ISSUE THREAD

**Issue by petek** [darktrojan/shrunked#23]
When using Shrunked 4.4 with SeaMonkey 2.40, image resizing in emails has stopped working.  When attaching the photo, it asks to resize, but then doesn't follow through.  The error console shows the following log:

> Resizing started
> Resizing to 500 x 500, 75 quality
> No valid EXIF data
> FileReader is not defined (Shrunked.jsm, line 48)
> Resizing complete

![shrunkederror](https://cloud.githubusercontent.com/assets/126508/21404049/fec4bb9c-c784-11e6-8c58-3e0fd300ff8e.png)

**Comment by petek** [comment]
This is new to 4.4; shrinking was working in 4.32.

**Comment by darktrojan** [comment]
That's a surprising error. Also, I thought I'd tested the new stuff on SeaMonkey, clearly I had not.
