### ISSUE TITLE
Error sending email: nsIMsgCompDeliverMode is not defined

### ISSUE THREAD

**Issue by petek** [darktrojan/shrunked#24]
I can't send email using SeaMonkey 2.46 with shrunked 4.4.1 enabled; I get the following error:

![nslmsgcompdelivermode](https://cloud.githubusercontent.com/assets/126508/21531986/b8acf8e4-cd11-11e6-936f-faf218868d82.png)

Error: ReferenceError: nsIMsgCompDeliverMode is not defined
Source File: chrome://shrunked/content/compose.js
Line: 376

**Comment by darktrojan** [comment]
Hmm, that's new! TBH I haven't had time to test SeaMonkey 2.46 properly since it was released.

This appears to be an easy fix so I'll do it now. Thanks for your report and your donation!
