### ISSUE TITLE
Default settings cannot be saved

### ISSUE THREAD

**Issue by syldub69** [darktrojan/shrunked#31]
Hi,
If we set different default settings, the settings are not saved. When we open the default settings again, the last configuration is not remembered.
Though the advanced options are well saved.
I am using Shrunked Image Resizer 4.5.5 on Thunderbird 68.4.2 (64-bit).

**Comment by syldub69** [comment]
This issue seems to be fixed in version 5.0.0.

**Comment by therob84** [comment]
I still find that not ALL settings are saved properly in v. 5.0.0 / TB78.4.0, as I also quoted here: https://github.com/darktrojan/shrunked/issues/36#issuecomment-717809375
"Settings are not properly saved: minimal file size for resize: 100 kb –> changing to 200 kb is not saved after reopen settings"
