### ISSUE TITLE
Port this extension to FireFox ?

### ISSUE THREAD

**Issue by jpyrat** [darktrojan/shrunked#40]
Hi,

do you have plans to port this to Firefox (and Chrome) ?

There was a version for FireFox before : http://www.softsea.com/review/Shrunked-Image-Resizer.html

Regards

**Comment by darktrojan** [comment]
You're correct that there was a Firefox version before. I stopped making it a long time ago and have no intention of starting it again. It just became more and more useless as the popular websites implemented custom uploaders that Shrunked couldn't work with, which leads to tons of complaints that it "doesn't work with XYZ". It was a waste of my time in the end.

**Comment by mMuck** [comment]
So this could be closed, right?
