### ISSUE TITLE
Mail not sent if Original is checked

### ISSUE THREAD

**Issue by jpcasta** [darktrojan/shrunked#41]
Hello,
If I want to send the mail without resizing the images, I check the 'Original' option but the mail is not sent when I click the OK button. (see picture)
Thanks
Regards

![Options de Shrunked Image Resizer](https://user-images.githubusercontent.com/58230543/102719303-a18d3380-42ed-11eb-8756-2ad7dde72e6c.jpg)

**Comment by guebert** [comment]
I confim this behaviour!
Please fix it.

(Work around: set the custom size bigger than the original size of the picture, then the message will be sent!)

Michael

**Comment by jpcasta** [comment]
Yes that is correct regarding the work around but it increases also the size of the attached picture.
I guess it is a minor change that has to be done to send the mail without changing the picture.... ;-)
Regards

**Comment by darktrojan** [comment]
This is now fixed. Just waiting for a human to come along and approve the update.

**Comment by jpcasta** [comment]
Hello,
It works correctly!
Thanks for your help
Regards
