### ISSUE TITLE
TB91: Context Menu has no function

### ISSUE THREAD

**Issue by somjue** [darktrojan/shrunked#45]
With TB91 the context menu item to resize an image has no effect (shrink dialog does not appear, no message in console), so I can't resize an image.
When I paste an image from clipboard, the inline bar on the bottom works well: the message appears and when I click to "yes", the shrink dialog comes up and works like a charm. So the extension is working, only the click on the context menu item is not recognized.
Thanks for your support and the very useful extension!

**Comment by darktrojan** [comment]
You're right, Thunderbird 91 broke that. Thanks.
