### ISSUE TITLE
Unmaintained translations at risk of removal

### ISSUE THREAD

**Issue by darktrojan** [darktrojan/shrunked#8]
I've decided that it's not worth maintaining the translations which haven't been updated for a long time. They are likely to be removed.

At risk: Catalan, ~~German~~, ~~French~~, ~~Italian~~, Polish, Portuguese (Brazil), Swedish, Turkish, Chinese (Simplified). Each of these is missing a large number of strings.

I don't want to annoy a lot of users by having their software revert to English, but I think they would rather have it all in English than half (or more) in English, half in another language.

If you can help, send a pull request, or visit https://zoo2translate.herokuapp.com/darktrojan/shrunked, which makes the process easier.

**Comment by darktrojan** [comment]
I've just pushed 7f3b3c015518dd9cb9edfc0b557f22e4d2bc75e2, which leads here. If you clicked a button which led you here, it looks like it worked!

**Comment by darktrojan** [comment]
Thanks @ND83 for updating the French translation!

**Comment by TomBrixton** [comment]
I can help you with the german translation.

**Comment by darktrojan** [comment]
Thanks @TomBrixton – although it looks like somebody has [already done it](http://zoo.darktrojan.net/darktrojan/shrunked/de/locale.php).

**Comment by TomBrixton** [comment]
Ok, but the bars are not completely green, doesn't that mean there is still something missing?

**Comment by darktrojan** [comment]
Not necessarily, some of the strings are just the same as they are in English. That's okay.
